#!/usr/bin/env python
"""
Generates and outputs an updates overrides.py file from the IANA bootstrap data.
This uses the data generated by https://github.com/case/iana-data (Thanks @case!).

Usage:
    uv run tools/generate_overrides_from_iana_data.py > whoisit/overrides.py
"""

import sys
from pathlib import Path



parent_dir = Path(__file__).resolve().parent.parent
sys.path.append(str(parent_dir))


from datetime import datetime, timezone
import json
import requests
from whoisit.logger import get_logger  # noqa: E402


log = get_logger("tools")
CCTLD_SUPPLEMENTAL: str = 'https://raw.githubusercontent.com/case/iana-data/refs/heads/main/data/manual/supplemental-cctld-rdap.json'
OVERRIDES_TEMPLATE: str = '''
"""
Various RDAP servers are either incorrect or not listed in the IANA
bootstrap data. This file contains a list of overrides that are overlayed
onto the IANA data by default.

Last updated: {updated}
"""


iana_overrides: dict[str, ...] = {{
    "domain": {overrides}
}}
'''.strip()

if __name__ == "__main__":
    log.info(f"Fetching supplemental ccTLDs from: {CCTLD_SUPPLEMENTAL}")
    data = requests.get(CCTLD_SUPPLEMENTAL).json()
    overrides: dict[str, list[str]] = {}
    for cctld in data.get('ccTldRdapServers', []):
        tld = cctld.get('tld')
        rdap_endpoint = cctld.get('rdapServer')
        if tld and rdap_endpoint:
            overrides[tld] = [rdap_endpoint]
    overrides_str = json.dumps(overrides, indent=4)
    overrides_str = '\n    '.join(overrides_str.splitlines())
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:00 UTC")
    print(OVERRIDES_TEMPLATE.format(
        overrides=overrides_str,
        updated=updated
    ))
    log.info("Done")
